### ISSUE TITLE
🗑️ Remove Serilog dependencies in logging packages 

### ISSUE THREAD

**Issue by stijnmoreels** [arcus-azure/arcus.testing#212]
**Is your feature request related to a problem? Please describe.**
In the past, when the Testing.Logging package was mostly internally used, we had introduced a Serilog variant to test out things in and test transactional correlation. But since this is now more publicly used, it does not seem right to force Serilog dependencies in these logging packages.

**Describe the solution you'd like**
Deprecate the Serilog references in the Logging.* packages.

**Describe alternatives you've considered**
None seems approporiate. We should strive towards minimal dependencies, and if people want to have custom test logging, they can still do this by building on top of our `Il

**Additional context**
The dependency is a transient one in the Logging.Core package.

> 💡 It would also be best that we stop releasing this package separately and guide people towards the test framework-specific ones.

**Action plan**
- [x] Deprecate `Arcus.Testing.Logging.Core` on NuGet (v1.2 and lower);
- [x] Stop building package for `Arcus.Testing.Logging.Core` (v1.3) (#231);
- [x] Mark Serilog sinks in test framework packages as `[Obsolete]` (v1.3) (#231);
- [x] Remove Serilog sinks in test framework packages (v2.0);
- [x] Remove Serilog packages from `Arcus.Testing.Logging.Core` (v2.0).

**Comment by stijnmoreels** [comment]
- [ ] Deprecate `Arcus.Testing.Logging.Core` on NuGet (v1.3);
- [ ] Stop building package for `Arcus.Testing.Logging.Core` (v1.3);
- [ ] Mark Serilog sinks in test framework packages as `[Obsolete]` (v1.3);
- [ ] Remove Serilog sinks in test framework packages (v2.0);
- [ ] Remove Serilog packages from `Arcus.Testing.Logging.Core` (v2.0).

**Comment by stijnmoreels** [comment]
Done implicitly by referenced PR's.
